### ISSUE TITLE
feat: 투표 버튼 스타일 및 기능

### ISSUE THREAD

**Issue by dle234** [Step3-kakao-tech-campus/Team11_FE#2]
## Issue: FEATURE

버튼 컴포넌트

## Description

버튼 스타일과 기능 관련 이슈

## Todo
- [x]  스타일
   - [x]  버튼 기본 style (background : rgba(255, 255, 255, 1), color: rgba(103, 103, 103, 1)) , 높이 고정, 글자 초과시 너비 늘리기
   - [x]  버튼 클릭 시 style( b: rgba(172, 192, 255, 0.5), c: 2D53CF) , 아래 퍼센트 글씨

- [x] 기능 및 투표
  - [x] 클릭 시 요청 보내고, res로 게이지 받아오기 (put?) + 바로 스타일 변경하기 + 애니메이션 약간 넣어주기
  - [x] 버튼 클린한것은 파란색, 클릭 안한거는 회색으로 결과 보여주기. 그 버튼만 이 아니라 버튼 전체 상태 변화주기.
  - [x] 버튼 클릭된 상태에서 또 클릭하면 (혹은 다른 버튼) 수정할 수 없습니다 라는 alert 창 띄우기 or 아예 안눌리게 하기.
  - [x] 버튼 위에 이미지 넣을 수 있는 컴포넌트 하나 만들어놓기

- [x] 로그인 상태 O X
  - [x] 유저가 투표 한 상태인지 아닌지 확인 후 상태에 따른 style 보여주기
  - [x] 로그인 하지 않은 유저의 경우 투표 시 알람창 뜨고, 로그인창으로 리다이렉트
 

## ETC

기타사항

**Comment by dle234** [comment]
끝!
