### ISSUE TITLE
feat: 상단/하단 navBar 구현

### ISSUE THREAD

**Issue by ketru44** [Step3-kakao-tech-campus/Team11_FE#4]
## Issue: FEATURE
상단/하단 네비게이션바 구현

## Description
- 상단 navBar 구현(필터, 검색 버튼)
- 하단 navBar 구현(홈, 핫게, 투표생성, 완료된 질문, 로그인(마이페이지))
## Todo

- [x]  상단바(Header) 
  - [x] 필터1(최신순(default), 인기순)
  - [x] 필터2(카테고리 별)
  - [x] 필터 클릭 시 list 보여주고 다른 선택지 클릭 시 요청 ( + 다른 부분 클릭 시 원상태로??)
 
- [x]  하단바(Footer)
  - [x] 홈(default)
  - [x] 핫게
  - [x] 투표 생성
  - [x] 완료된 질문
  - [x] 로그인 (마이페이지)
  - [x] 클릭 시 색 변경 (7192FF),  이동 , 상단 바 변경

- [ ] 변경된 상단바 ( 홈 이외의 페이지)
  - [ ] 뒤로 가기 버튼
  - [ ] 페이지 이름
  - [ ] 검색 버튼 

## ETC

기타사항

**Comment by mun-jihye** [comment]
## 변경된 상단바
페이지마다 헤더는 다 다르게 들어가고, footer는 같게 들어가기
