### ISSUE TITLE
feat: 투표 상세 페이지 댓글 기능

### ISSUE THREAD

**Issue by mun-jihye** [Step3-kakao-tech-campus/Team11_FE#58]
## Description
투표 상세 페이지에서 상대방의 댓글을 확인할 수 있고, 댓글을 작성할 수 있다.

## Todo
- [x] 상대방의 댓글 보여주기 (상대방의 프로필 사진, 댓글 내용)
- [x] 댓글 작성 기능
- [x] 댓글 작성 후 전송 버튼 구현
- [x] 나의 프로필 사진 보여주기 

## 기타사항
없음
